In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  

def linear_svm():
    # download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
    # info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

    # load data
    bankdata = pd.read_csv("bill_authentication.csv")  

    # see the data
    bankdata.shape  

    # see head
    bankdata.head()  

    # data processing
    X = bankdata.drop('Class', axis=1)  
    y = bankdata['Class']  

    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='linear')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))

linear_svm()

[[154   3]
 [  4 114]]
             precision    recall  f1-score   support

          0       0.97      0.98      0.98       157
          1       0.97      0.97      0.97       118

avg / total       0.97      0.97      0.97       275



In [35]:
from sklearn.svm import SVC  


# Iris dataset  https://archive.ics.uci.edu/ml/datasets/iris4
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  
    return X_train, X_test, y_train, y_test
    
def polynomial_kernel(X_train, X_test, y_train, y_test):
    # TODO
    # NOTE: use 8-degree in the degree hyperparameter. 
    # Trains, predicts and evaluates the model
        # train the SVM
    svclassifier = SVC(kernel='poly', degree = 8)  
    svclassifier.fit(X_train, y_train)  
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix 
    print("Polynomial Kernal")
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))

def gaussian_kernel(X_train, X_test, y_train, y_test):
    # TODO
    # Trains, predicts and evaluates the model
    svclassifier = SVC(kernel='rbf')  
    svclassifier.fit(X_train, y_train)  
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Gaussian Kernal")
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))

def sigmoid_kernel(X_train, X_test, y_train, y_test):
    # TODO
    # Trains, predicts and evaluates the model
    svclassifier = SVC(kernel='sigmoid')  
    svclassifier.fit(X_train, y_train)  
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print("Sigmoid Kernal")
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))
        


def test():
    X_train, X_test, y_train, y_test = import_iris()
    polynomial_kernel(X_train, X_test, y_train, y_test)
    gaussian_kernel(X_train, X_test, y_train, y_test)
    sigmoid_kernel(X_train, X_test, y_train, y_test)
    # NOTE: 3-point extra credit for plotting three kernel models.

test()

Polynomial Kernal
[[ 9  0  0]
 [ 0  8  1]
 [ 0  2 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.80      0.89      0.84         9
 Iris-virginica       0.91      0.83      0.87        12

    avg / total       0.90      0.90      0.90        30

Gaussian Kernal
[[ 9  0  0]
 [ 0  8  1]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.89      0.89      0.89         9
 Iris-virginica       0.92      0.92      0.92        12

    avg / total       0.93      0.93      0.93        30

Sigmoid Kernal
[[ 5  4  0]
 [ 9  0  0]
 [12  0  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.19      0.56      0.29         9
Iris-versicolor       0.00      0.00      0.00         9
 Iris-virginica       0.00      0.00      0.00        12

    avg / total       0.06      0.